### ISSUE TITLE
Build on top of official unit test framework?

### ISSUE THREAD

**Issue by Ciantic** [nb/wordpress-tests#8]
Hi!

There exists [official test framework for WordPress](http://codex.wordpress.org/Automated_Testing)

What are the reasons you have written this framework? Is it because better view of results? I would like to have a better results view but for me it is more important to have supported unit test framework. It kind of makes no sense on building on top of third party framework that most likely will ran out of support soon enough.

Right now the files are over 6 months old, and support for your framework may have been dried out? So I suggest you try again building your stuff on top of the official framework, or enhancing it.

**Comment by scribu** [comment]
This suite is meant to _replace_ the existing one, since it runs a lot faster. Both are built on top of `phpunit`, so they're not that different.

**Comment by Ciantic** [comment]
It cannot replace it until the official tests can be run with your framework. After that maybe support for your framework will be provided by the WordPress team?

**Comment by scribu** [comment]
> It cannot replace it until the official tests can be run with your framework.

Indeed, which will be a fair amount of work. Patches welcome.

**Comment by nb** [comment]
The goal of building this framework was to build a framework which:
- Is Faster
- Runs every test case in a clean WordPress install
- Uses the default PHPUnit runner, instead of custom one
- Doesn't encourage or support the usage of Shared/Prebuilt fixtures

The core devs have generally agreed that this is the way to go, but rebuilding the test suite is far from their priority and in the meantime my priorities also changed and I have more important/interesting stuff to do than push for this project to become the de-facto suite and to move some of the test/rewrite some of the old ones.
